apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-mongodb
spec:
  schedule: "0 */1 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          
          containers:
          - name: backup-mongodb
            image: ghcr.io/sysnor/k8s-backup-mongodb:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-uri
                  key: MONGODB_URI              

            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: BUCKET_NAME
            
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_SECRET_ACCESS_KEY

            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_DEFAULT_REGION

            # Below is optional

            - name: BUCKET_PREFIX
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: BUCKET_PREFIX

            - name: AWS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: AWS_ENDPOINT
            
            - name: OBJECT_LOCK_DAYS
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: OBJECT_LOCK_DAYS
             
